const icons = {
  Tormenta: "iconos/animated/thunder.svg",
  Lluvioso: "iconos/animated/rainy-2.svg",
  Lluvia: "iconos/animated/rainy-7.svg",
  Nieve: "iconos/animated/snowy-6.svg",
  Despejado: "iconos/animated/day.svg",
  "Poco nuboso": "iconos/animated/cloudy-day-1.svg",
  "Nubes altas": "iconos/animated/cloudy-day-2.svg",
  Nuboso: "iconos/animated/cloudy-day-3.svg",
  "Muy nuboso": "iconos/animated/cloudy.svg",
  Cubierto: "iconos/animated/cloudy.svg",
  Bruma: "iconos/animated/fog.svg",
  Niebla: "iconos/animated/mist.svg",
  Calima: "iconos/animated/haze.svg",
  Granizo: "iconos/animated/hail.svg",
  Chubascos: "iconos/animated/showers.svg",
  "Intervalos nubosos con lluvia": "iconos/animated/rainy-3.svg",
  "Intervalos nubosos con nieve": "iconos/animated/snowy-2.svg",
  "Intervalos nubosos": "iconos/animated/cloudy-day-2.svg",
  "Intervalos nubosos con lluvia escasa": "iconos/animated/rainy-1.svg",
  "Intervalos nubosos con tormenta y lluvia escasa":
    "iconos/animated/rainy-1.svg",
  "Nuboso con tormenta y lluvia escasa": "iconos/animated/rainy-2.svg",
  "Nuboso con lluvia": "iconos/animated/rainy-2.svg",
  "Muy nuboso con lluvia": "iconos/animated/rainy-1.svg",
  "Nuboso con lluvia escasa": "iconos/animated/rainy-4.svg",
  "Muy nuboso con lluvia escasa": "iconos/animated/rainy-4.svg",
  "Cubierto con lluvia": "iconos/animated/rainy-4.svg",
  "Nuboso con nieve": "iconos/animated/snowy-5.svg",
  "Muy nuboso con nieve": "iconos/animated/snowy-6.svg",
  "Sin datos": "iconos/animated/day.svg", // Icono por defecto
};
